#!/usr/bin/env bash
# what’s keeping my Ubuntu container’s Nginx installation from listening on port 8?
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
